### ISSUE TITLE
Немного замечаний

### ISSUE THREAD

**Issue by spiridonovaalexis** [DS-83/golang-restful-api#1]
1. Не очень информативно называть "e" пакет
2. Лучше переложить revoked_tokens в nosql бд
3. [header := h["Authorization"]](https://github.com/DS-83/golang-restful-api/blob/ea45604c6dcf524d553ae3a1aa4edfd91928648e/auth/delivery/http/handlers.go#L117)
Надо в константы выносить все строки
И можно `h.Get(key)` воспользоваться

4. https://github.com/DS-83/golang-restful-api/blob/ea45604c6dcf524d553ae3a1aa4edfd91928648e/auth/delivery/http/handlers.go#L115

Так делать не нужно
Лучше оборачивать ошибку снаружи
```
cred, err := parseSignInHeader(c.Request.Header)
if err != nil {
	return e.Wrap("can't read authorization param", err)
}
```

5. https://github.com/DS-83/golang-restful-api/blob/ea45604c6dcf524d553ae3a1aa4edfd91928648e/auth/delivery/http/middleware.go#L61

`If len(s) != 2`

6. https://github.com/DS-83/golang-restful-api/blob/ea45604c6dcf524d553ae3a1aa4edfd91928648e/auth/delivery/http/handlers.go#L82

Можно тут ведь тоже в структуру завернуть

7. https://github.com/DS-83/golang-restful-api/blob/ea45604c6dcf524d553ae3a1aa4edfd91928648e/models/photo.go#L28

Лучше вынести в utils

8. https://github.com/DS-83/golang-restful-api/blob/ea45604c6dcf524d553ae3a1aa4edfd91928648e/auth/delivery/http/handlers_test.go#L20

структуру лучше вынести из функции теста

**Comment by DS-83** [comment]
1. Переименовал в "err".
2. Done.
3. Завел константу authHeader. h.Get(key) возвращает string, h[key] возвращает []string. Оставил, чтобы не усложнять.
4. Остался артефакт после отладки. Исправил.
5. Done.
6. Done.
7. Вынес в пакет utils.
8. Done
9. Исправил маршрут /delete/user --> /user/delete

**Comment by DS-83** [comment]
Fixed.
